language: php

php:
  - "5.4"
  - "5.3"

env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

matrix:
  allow_failures:
    - php: 5.4

before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS wolfcms_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database wolfcms_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'DROP DATABASE IF EXISTS wolfcms_test;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database wolfcms_test;'; fi"
  - git clone --depth=100 --quiet git://github.com/wolfcms/wolfcms-phpunit.git test
  - cd test

script: phpunit --configuration phpunit.travisci.xml
